version: '3.3'

services:
  db: 
   image: postgres:14
   container_name: ecommerceContaint
   environment:
    - POSTGRES_USER=admin
    - POSTGRES_DB=ecommercedb
    - POSTGRES_PASSWORD=admin_123
   ports:
    - 5433:5432
   volumes:
    - ./data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kalet.svdev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_123